import {test,expect} from "@playwright/test"
test("ibm",async({page})=>{
    test.slow()
    await page.goto("https://www.spicejet.com/")
    // await page.locator('//div[@class="r-1862ga2 r-1loqt21 r-1i10wst r-tceitz r-u8s1d css-76zvg2"]').click()
    // await page.getByTestId('to-testID-destination').getByRole('textbox').pressSequentially("be")
    // await page.locator("//div[.='To']/following-sibling::div").click()
    // await page.locator('//div[text()="To"]').click()
    await page.locator('//div[@data-testid="to-testID-destination"]').click()
    await page.keyboard.insertText('Be')
    // await page.locator("//div[@class='css-1dbjc4n r-14lw9ot r-z2wwpe r-1rjd0u6 r-1g94qm0 r-u8s1d r-8fdsdq']/descendant::div[text()='Bengaluru']").click()
    await page.getByText('Departure Date').click()
    // await page.locator('//div[text()="Wed, 12 Feb 2026"]').click()
    await page.locator('//div[@data-testid="home-page-travellers"]').click()
    await page.locator('//div[@data-testid="Adult-testID-plus-one-cta"]').click()
    await page.locator('//div[@data-testid="home-page-flight-cta"]').click()
    // await page.locator('//img[@src="https://www.spicejet.com/loader.gif"]').waitFor({state: 'detached'})
    await page.locator("//div[@id='onward-flight-container']/div").nth(0).waitFor({state: 'visible'})
    // let a=await page.locator("//div[@id='onward-flight-container']/div").all()
    let a=await page.locator("//div[@id='onward-flight-container']/div").count()
    console.log(a)
 })
